#include "ConstGlobals.h"
HWND					hWndGlobal;
HINSTANCE				hInstanceGlobal;
Game*					gameGlobal;
CKey*					keyGlobal;
CTextures*				texturesGlobal;
CSprites*				spritesGlobal;
CAnimations*			animationsGlobal;
Camera*					cameraGlobal;
Viewport*				viewPortGlobal;
LPDIRECTINPUTDEVICE8	didvGlobal;
LPDIRECTINPUT8			dinputGlobal;
